site_name: "Math’Lab"
site_description: "Projet pédagogique de laboratoire de mathématiques en classe de 6e"
site_url: "https://olef9.github.io/Mathlab/"

repo_name: "olef9/Mathlab"
repo_url: "https://github.com/olef9/Mathlab"
edit_uri: ""

docs_dir: docs
site_dir: site

theme:
  name: material
  language: fr
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: fr

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true